apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30081
  selector:
    app: nginx
